# Generated by Django 5.0.2 on 2024-03-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                default="0999999999", max_length=30, verbose_name="Phone Number"
            ),
        ),
    ]
