# Generated by Django 5.0.2 on 2024-03-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                default="+41524204242", max_length=30, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/download.png", upload_to="", verbose_name="Profile Photo"
            ),
        ),
    ]
