# Generated by Django 5.0.2 on 2024-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/user.png",
                upload_to="user_images/",
                verbose_name="Profile Photo",
            ),
        ),
    ]
