# Generated by Django 5.0.2 on 2024-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_profile_photo"),
        ("properties", "0010_property_cover_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_locations",
            field=models.ManyToManyField(to="properties.location"),
        ),
    ]
