# Generated by Django 5.0.2 on 2024-06-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_profile_preferred_locations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preferred_locations",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
