# Generated by Django 5.0.2 on 2024-07-03 10:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_profile_preferred_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=cloudinary.models.CloudinaryField(
                default="/user.png", max_length=255, verbose_name="Profile Photo"
            ),
        ),
    ]
