# Generated by Django 5.0.2 on 2024-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
