# Generated by Django 5.0.2 on 2024-03-06 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_customuser_activation_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="activation_code",
        ),
    ]
