# Generated by Django 5.0.2 on 2024-03-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(default=1, verbose_name="Bathrooms"),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(default=1, verbose_name="Bedrooms"),
        ),
        migrations.AddField(
            model_name="property",
            name="kitchens",
            field=models.IntegerField(default=1, verbose_name="Kitchens"),
        ),
        migrations.AddField(
            model_name="property",
            name="living_rooms",
            field=models.IntegerField(default=1, verbose_name="Living rooms"),
        ),
        migrations.AddField(
            model_name="property",
            name="total_floors",
            field=models.IntegerField(default=0, verbose_name="Number of floors"),
        ),
    ]
