# Generated by Django 5.0.2 on 2024-03-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_location_property_location_propertyviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="location",
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(default="t", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="published_status",
            field=models.BooleanField(default=False, verbose_name="Published Status"),
        ),
        migrations.AddField(
            model_name="property",
            name="region",
            field=models.CharField(default="t", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="street",
            field=models.CharField(default="t", max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
