# Generated by Django 5.0.2 on 2024-04-09 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertypictures",
            name="property_id",
        ),
        migrations.AddField(
            model_name="propertypictures",
            name="property",
            field=models.ForeignKey(
                default=18,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="properties.property",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="/house.jpg",
                null=True,
                upload_to="",
                verbose_name="Main Photo",
            ),
        ),
        migrations.AlterField(
            model_name="propertypictures",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
    ]
