# Generated by Django 5.0.2 on 2024-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_status",
            field=models.CharField(
                choices=[("For Sale", "For Sale"), ("For Rent", "For Rent")],
                default="For Sale",
                max_length=50,
                verbose_name="Property Status",
            ),
        ),
    ]
