# Generated by Django 5.0.2 on 2024-03-30 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_alter_location_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table=None,
        ),
    ]
