# Generated by Django 5.0.2 on 2024-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_propertyimages_delete_propertypictures"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyimages",
            options={
                "verbose_name": "Images For Property",
                "verbose_name_plural": "Property Images",
            },
        ),
        migrations.AlterField(
            model_name="property",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="/house.jpg",
                null=True,
                upload_to="property_main_images/",
                verbose_name="Main Photo",
            ),
        ),
    ]
