# Generated by Django 5.0.2 on 2024-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_alter_location_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                    ("Villa", "Villa"),
                    ("Office", "Office"),
                    ("Chalet", "Chalet"),
                    ("Commercial", "Commercial"),
                    ("Farm", "Farm"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
                verbose_name="Property Type",
            ),
        ),
    ]
