# Generated by Django 5.0.2 on 2024-04-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_alter_propertyimages_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="floor_number",
            field=models.IntegerField(default=0, verbose_name="Number of floor"),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("بيت", "House"),
                    ("Apartment", "Apartment"),
                    ("Villa", "Villa"),
                    ("Office", "Office"),
                    ("Chalet", "Chalet"),
                    ("Commercial", "Commercial"),
                    ("Farm", "Farm"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
                verbose_name="Property Type",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_floors",
            field=models.IntegerField(default=0, verbose_name="Numbers of floors"),
        ),
    ]
