# Generated by Django 5.0.2 on 2024-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_property_covering_property_direction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="furnishings",
        ),
        migrations.RemoveField(
            model_name="property",
            name="ptype",
        ),
        migrations.AddField(
            model_name="property",
            name="furnishing",
            field=models.CharField(
                choices=[
                    ("مفروش", "مفروش"),
                    ("نص مفروش", "نص مفروش"),
                    ("غير مفروش", "غير مفروش"),
                ],
                default="غير مفروش",
                verbose_name="الفرش",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="ownership_type",
            field=models.CharField(
                choices=[
                    ("طابو أخضر", "طابو أخضر"),
                    ("عقد بيع قطعي", "عقد بيع قطعي"),
                    ("حكم محكمة", "حكم محكمة"),
                    ("وكالة كاتب بالعدل", "وكالة كاتب بالعدل"),
                    ("طابو أسهم", "طابو أسهم"),
                    ("طابو زراعي", "طابو زراعي"),
                    ("طابو إسكان", "طابو إسكان"),
                    ("فروغ", "فروغ"),
                ],
                default="طابو أخضر",
                max_length=50,
                verbose_name="نوع الملكية",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="rent_type",
            field=models.CharField(
                blank=True,
                choices=[("شهري", "شهري"), ("يومي", "يومي")],
                default="شهري",
                null=True,
                verbose_name="نوع الأجار",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("شرق", "شرق"),
                    ("غرب", "غرب"),
                    ("شمال", "شمال"),
                    ("جنوب", "جنوب"),
                    ("الشمال الشرقي", "الشمال الشرقي"),
                    ("الشمال الغربي", "الشمال الغربي"),
                    ("الجنوب الشرقي", "الجنوب الشرقي"),
                    ("الجنوب الغربي", "الجنوب الغربي"),
                ],
                null=True,
                verbose_name="الاتجاه",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("House", "بيت"),
                    ("Apartment", "شقة"),
                    ("Villa", "فيلا"),
                    ("Office", "مكتب"),
                    ("Chalet", "شاليه"),
                    ("Market", "تجاري"),
                    ("Farm", "مزرعة"),
                    ("Building", "بناء"),
                    ("Land", "أرض"),
                    ("Other", "اخر"),
                ],
                default="Other",
                max_length=50,
                verbose_name="Property Type",
            ),
        ),
    ]
