# Generated by Django 5.0.2 on 2024-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0007_remove_property_furnishings_remove_property_ptype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="user_type",
            field=models.CharField(
                choices=[("مالك", "مالك"), ("تاجر", "تاجر")],
                default="مالك",
                max_length=50,
                verbose_name="نوع البائع",
            ),
        ),
    ]
