# Generated by Django 5.0.2 on 2024-06-14 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_property_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="cover_photo",
        ),
    ]
