# Generated by Django 5.0.2 on 2024-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_remove_property_cover_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="/house.jpg",
                null=True,
                upload_to="property_main_images/",
                verbose_name="Main Photo",
            ),
        ),
    ]
