# Generated by Django 5.0.2 on 2024-07-03 10:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_property_cover_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="cover_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="/house.jpg",
                max_length=255,
                null=True,
                verbose_name="Main Photo",
            ),
        ),
        migrations.AlterField(
            model_name="propertyimages",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
