# Generated by Django 5.0.2 on 2024-07-05 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_userpropertyfavorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userpropertyfavorite",
            unique_together={("user", "property")},
        ),
    ]
