# Generated by Django 5.0.2 on 2024-07-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0013_alter_userpropertyfavorite_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_status",
            field=models.CharField(
                choices=[("للبيع", "بيع"), ("للأجار", "أجار")],
                default="للبيع",
                max_length=50,
                verbose_name="Property Status",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("بيت", "بيت"),
                    ("شقة", "شقة"),
                    ("فيلا", "فيلا"),
                    ("مكتب", "مكتب"),
                    ("شاليه", "شاليه"),
                    ("تجاري", "تجاري"),
                    ("مزرعة", "مزرعة"),
                    ("بناء", "بناء"),
                    ("أرض", "أرض"),
                    ("اخر", "اخر"),
                ],
                default="اخر",
                max_length=50,
                verbose_name="Property Type",
            ),
        ),
    ]
