# Generated by Django 5.0.2 on 2024-07-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0014_alter_property_property_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_status",
            field=models.CharField(
                choices=[("للبيع", "للبيع"), ("للأجار", "للأجار")],
                default="للبيع",
                max_length=50,
                verbose_name="Property Status",
            ),
        ),
    ]
