# Generated by Django 5.0.2 on 2024-07-08 00:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0015_alter_property_property_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="cover_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/dl9tgk3vr/image/upload/v1720397484/dgdtgymdj0nuqcooi4ko.jpg",
                max_length=255,
                null=True,
                verbose_name="Main Photo",
            ),
        ),
    ]
