# Generated by Django 5.0.2 on 2024-03-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="auth_provider",
            field=models.CharField(
                default="Email", max_length=50, verbose_name="Auth Provider"
            ),
        ),
    ]
