# Generated by Django 5.0.2 on 2024-03-17 15:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_number",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Property Number",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(default="Homs", max_length=180, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="property",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="/house.jpeg",
                null=True,
                upload_to="",
                verbose_name="Main Photo",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="region",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Region"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="street",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Street Address"
            ),
        ),
        migrations.CreateModel(
            name="PropertyPictures",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="/house.jpg", null=True, upload_to=""
                    ),
                ),
                (
                    "property_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Pictures",
        ),
    ]
